### ISSUE TITLE
Training specifications for Figure B from the paper

### ISSUE THREAD

**Issue by saocorley** [kimren227/CSGStumpNet#14]
Hello! Loved your work.
We are trying to use this model to generate simple CSG trees (or stumps I guess) but I have struggled to get the same results you show in the paper when training from scratch.
When you used 16 primitives and 16 intersections nodes, did you train the network with only one airplane, or with the entire dataset? Also, do you happen to remember the hiper parameters? 
Thank you, and again, amazing work.

**Comment by kimren227** [comment]
Hi,

Thanks for your interest in our work. Yes, it is only trained with airplane class with 16 primitive and intersection nodes. Other hyper-parameters are aligned with the rest of the paper. 

Let me know if this helps.

Best, Daxuan

**Comment by saocorley** [comment]
Hello!
Thanks for the fast reply. 
We have been training with these hyper-parameters:
```
{
    "Discription": "Use occupancy",
    "num_primitives": 16,
    "num_intersections": 16,
    "epoch": 100001,
    "learning_rate":0.0001,
    "beta1":0.9,
    "feature_dim": 256,
    "real_size": 128,
    "test_size": 16,
    "num_gpu":2,
    "train_batch_size_per_gpu": 2,
    "test_batch_size_per_gpu": 2,
    "eval_interval": 10,
    "num_surface_points": 2048,
    "num_sample_points": 2048,
    "balance": true,
    "category":"02691156",
    "sharpness":150.0,
    "sample_dir":"./samples/",
    "csg_dir":"./csgs/",
    "scale_primitive_loss":0.001,
    "dataset_root": "./data"
}
```
But the results are quite different. This is a plane we are getting (it is representative of most of the planes in the category, either in the train or test subset). This is the model after about 200 epochs, trained from scratch.
Are we missing something?
Thank you in advance,

<img width="275" alt="image" src="https://github.com/user-attachments/assets/cac86657-d135-4dfe-b5a2-be14a26ba4fa">

**Comment by saocorley** [comment]
Just realized it was a bug on my side, sorry! I am now testing it again with the proper code :)
