### ISSUE TITLE
Release code of complement layer

### ISSUE THREAD

**Issue by FENGGENYU** [kimren227/CSGStumpNet#2]
Hi, I am interested in your work.

However, I find the first complement layer code is missing in your code model.py.

Will you plan to release the code of that part?

Looking forward to your reply, thank you!

Best.

**Comment by kimren227** [comment]
Hi Fenggen,

Thanks for your interest. I also came across your work "CAPRI-Net" a few months ago and found it very interesting.

As stated in the "Implementation Details" of the paper, adding a complement layer only increase the performance (quantitatively) slightly, however, with the cost of more computation, a larger learning space, leading to a longer and more unstable training process (sometimes, weird results are generated, see attached). Hence, the complement layer is not included in this version of the code.

I can make a new branch with the complement layer ASAP. Hopefully, that helps.

![image](https://user-images.githubusercontent.com/8415809/132276955-c940749f-4459-4c81-a958-fab2476ea853.png)
![image](https://user-images.githubusercontent.com/8415809/132277416-1d01fa43-7e4f-4077-a050-542e7700cee5.png)

Best,

Daxuan

**Comment by FENGGENYU** [comment]
Hi, Daxuan.

Thanks for your reply. 

I am testing your model on ABC dataset, where I think the complement layer will be very helpful.

Looking forward to your new branch.

Best.

**Comment by kimren227** [comment]
Hi Fenggen,

I've created a new branch called "feature/with_complement". It should work, but I haven't thoroughly tested it yet.

Let me know if that solves your problem.

Best,

Daxuan

**Comment by kimren227** [comment]
Hi Fenggen,

I'll close this issue for now. If you got further questions, please reopen this issue.

Best,

Daxuan

**Comment by Farewell-ME** [comment]
> Hi, Daxuan.
> 
> Thanks for your reply.
> 
> I am testing your model on ABC dataset, where I think the complement layer will be very helpful.
> 
> Looking forward to your new branch.
> 
> Best.

hi, how is the performance on ABC dataset after complement layer is added?
