### ISSUE TITLE
Release pretrained weights

### ISSUE THREAD

**Issue by Christine0924** [kimren227/CSGStumpNet#3]
Hi, 

This is an interesting work and thanks for sharing your code!

I just want to know when will you share the pre-trained weights? I'd like to try it in my project!

Thank you!

**Comment by kimren227** [comment]
Hi Christine,

Thanks for your interest!

As we are reaching CVPR's deadline, computation resources are scarce. I haven't managed to retrain yet. I'll update you when the re-training is in progress. Should be later this month.

Best Regards,

Daxuan

**Comment by mikacuy** [comment]
Hi Daxuan,

Also following up on this. Can you please release the pretrained weights for your model?

Thanks,
Mika

**Comment by kimren227** [comment]
Hi Christine and Mikaela,

Really sorry for taking so long to reply.

I may have created some bugs during the refactor for the code release and my current training results are not good compared to the previous codebase. I'm looking into this issue as a priority.

In the meanwhile, I have manually adapted a previous weight for you to try out. Please check out the "previous_weights" branch and place the downloaded pre-trained weights under the CSGStumpNet root folder.

The checkpoint can be found: https://drive.google.com/drive/folders/1Hre-JswhCxkjEAxfwAST_FYzaAMcKVIx?usp=sharing

After that, you can run: `python eval.py --config ./configs/plane.json`

If everything went smoothly, you should get something like this:

<img width="635" alt="image" src="https://user-images.githubusercontent.com/8415809/152639617-b128fa45-7297-4a93-8b37-399662c5d2ac.png">

Let me know if you face any difficulties.

Best Regards,

Daxuan

**Comment by kimren227** [comment]
The pre-trained weights have been released. Please use the master branch.

If you need further assistance, please reopen this issue.

Best Regards,

Daxuan
