### ISSUE TITLE
Why do you use infinitely long cylinders and cones?

### ISSUE THREAD

**Issue by bluestyle97** [kimren227/CSGStumpNet#4]
Hi, thanks for your excellent work! But I'm confused that why you use infinitely long cylinders and cones when computing the sdf. Why there is no "height" parameter associated with these two types of primitives? I think they need to be bounded to form the final shape. Could you please explain this for me? Thank you in advance!

**Comment by kimren227** [comment]
Hi Jiale,

Thanks for your interest. 

There is no particular reason for infinitely long cylinders and cones. This is more a less a legacy issue (it is much easier to implement when cylinder and cone are unbounded). You are right, the individual cylinders and cones are not bounded shapes, but when intersecting with boxes or other types of primitives, the intersection result becomes bounded. 

Hope this helps,

Daxuan

**Comment by bluestyle97** [comment]
Thank you! I also notice that there is a `sdfPlane` function in `sdfs.py` but I didn't find it was used elsewhere. So I guess this function is useless for this project right?

**Comment by kimren227** [comment]
Yes, the sdfPlane is not used in the final project. It was implemented only for debug proposes.
