### ISSUE TITLE
question about avg_test_loss_recon

### ISSUE THREAD

**Issue by Farewell-ME** [kimren227/CSGStumpNet#9]
Hi daxuan,
   Why is the value avg_test_loss_recon divided twice by test_iter when printed to console as "loss_recon"? It occurs both in train.py and eval.py.
Best regards

**Comment by kimren227** [comment]
Oops, that's a bug😂 Would you like to make a PR for that?

**Comment by kimren227** [comment]
Fixed by [Farewell-ME]
